### ISSUE TITLE
NullPointerException in LocalSystemInfo when VERSION is not set in /etc/os-release

### ISSUE THREAD

**Issue by bwaldvogel** [mattjlewis/diozero#105]
According to the [documentation of /etc/os-release][1], the `VERSION` field is optional.

Arch Linux apparently does not set this field which causes the following `NullPointerException` in `LocalSystemInfo`: https://github.com/mattjlewis/diozero/blob/5c0b697693ac3c5ef0e0118c5896d68d67035a59/diozero-core/src/main/java/com/diozero/sbc/LocalSystemInfo.java#L268

```java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of "java.util.Properties.getProperty(String)" is null
        at com.diozero.sbc.LocalSystemInfo.<init>(LocalSystemInfo.java:268)
        at com.diozero.sbc.LocalSystemInfo.getInstance(LocalSystemInfo.java:244)
        at com.diozero.sbc.LocalBoardInfoUtil.initialiseLocalBoardInfo(LocalBoardInfoUtil.java:62)
        at com.diozero.sbc.LocalBoardInfoUtil.lookupLocalBoardInfo(LocalBoardInfoUtil.java:86)
        at com.diozero.util.LibraryLoader.loadSystemUtils(LibraryLoader.java:67)
        […]
```

[1]: https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by bwaldvogel** [comment]
Please see PR https://github.com/mattjlewis/diozero/pull/106 for my suggested fix.

**Comment by mattjlewis** [comment]
Brilliant - thank you. Will incorporate ASAP.
