### ISSUE TITLE
RPI5 says it's not supported

### ISSUE THREAD

**Issue by Danil0v3s** [mattjlewis/diozero#214]
Hey, been trying to use version 1.4.0 with a RPI5 8gb and it says "hardware revision is not supported"

```danil@raspberrypi:~/kRacing $ kmonitor
Warning: extension 'GL_ARB_invalidate_subdata' cannot be disabled
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ws2811_init failed: Hardware revision is not supported
java.lang.RuntimeException: Error initialising the WS281x strip
        at com.diozero.ws281xj.rpiws281x.WS281x.<init>(WS281x.java:154)
        at com.diozero.ws281xj.rpiws281x.WS281x.<init>(WS281x.java:121)
        at led.LedsController.controller_delegate$lambda$0(LedsController.kt:20)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at led.LedsController.getController(LedsController.kt:18)
        at led.LedsController.setIdle(LedsController.kt:51)
        at led.LedsController.<clinit>(LedsController.kt:47)
        at ui.app.AppViewModel$1$1.emit(App.kt:28)
        at ui.app.AppViewModel$1$1.emit(App.kt:27)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$filterIsInstance$$inlined$filter$2$2.emit(Emitters.kt:50)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:113)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:82)
        at repository.GameDataRepository$telemetry$1$1.invokeSuspend(GameDataRepository.kt:38)
        at repository.GameDataRepository$telemetry$1$1.invoke(GameDataRepository.kt)
        at repository.GameDataRepository$telemetry$1$1.invoke(GameDataRepository.kt)
        at repository.GameDataRepository$webSocket$3.invokeSuspend(GameDataRepository.kt:70)
        at repository.GameDataRepository$webSocket$3.invoke(GameDataRepository.kt)
        at repository.GameDataRepository$webSocket$3.invoke(GameDataRepository.kt)
        at io.ktor.client.plugins.websocket.BuildersKt.webSocket(builders.kt:101)
        at io.ktor.client.plugins.websocket.BuildersKt$webSocket$1.invokeSuspend(builders.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
^C#
```

**Comment by mattjlewis** [comment]
WS281x is not supported on the Pi5 - please see this [post](https://github.com/jgarff/rpi_ws281x/issues/528).

You can try the [Java SPI driver](https://github.com/mattjlewis/diozero/blob/main/diozero-ws281x-java/src/main/java/com/diozero/ws281xj/spi/WS281xSpi.java).

**Comment by EAGrahamJr** [comment]
FYI, you don't want to use coroutines with any of the hardware libraries -- they are not "suspendable" and you will end up with lots and lots of issues. If you stick with just Plain Ol' Threads, everything works quite well ([one of my "robotics" libraries](https://github.com/EAGrahamJr/kobots-parts/blob/main/Movements.md))
