### ISSUE TITLE
GPIO 0

### ISSUE THREAD

**Issue by neil-benn** [mattjlewis/diozero#67]
Hello,

  I'm running diozero on an RPi4 32 bit RpiOS with the direct memorymap provider.  I'm working on bit-banging the gpio pins and I need a lot of pins.  However, I have a problem trying to use GPIO 0.  I've got it set as output:

pi@rpi4-1:~ $ raspi-gpio get 0
GPIO 0: level=0 fsel=1 func=OUTPUT pull=DOWN

However when I try to run the diozero code to setup a DigitalOutputDevice I get the following stack trace:

Exception in thread "main" com.diozero.api.InvalidModeException: Invalid mode (digital output) for pin PinInfo [keyPrefix=GPIO, header=J8, deviceNumber=0, physicalPin=27, name=ID_SDA, chip=0, lineOffset=0, modes=[]]
        at com.diozero.internal.spi.GpioDeviceFactoryInterface.provisionDigitalOutputDevice(GpioDeviceFactoryInterface.java:74)
        at com.diozero.api.DigitalOutputDevice.<init>(DigitalOutputDevice.java:101)
        at com.diozero.api.DigitalOutputDevice.<init>(DigitalOutputDevice.java:85)
        at com.diozero.api.DigitalOutputDevice.<init>(DigitalOutputDevice.java:72)
        at com.diozero.api.DigitalOutputDevice.<init>(DigitalOutputDevice.java:61)
        at com.ziath.bitbang.BitbangStream.init(BitbangStream.java:40)
        at com.ziath.bitbang.TestGpio.main(TestGpio.java:12)

  GPIO 0 is ID_SDA but as far as I'm aware you can use it for output but can you maybe not memorymap it?

  Thanks for any help.

Cheers,

Neil

**Comment by mattjlewis** [comment]
I think I was being a bit overzealous protecting against default behaviour when these pins are assigned to I2C. I've addressed this in the board definition file here:
https://github.com/mattjlewis/diozero/blob/master/diozero-core/src/main/resources/boarddefs/raspberrypi.txt
This _should_ be picked up if you put it in a folder called "boarddefs" and add the parent folder to your classpath. I'll commit 1.1.8 with this fix in the next few days.
